### ISSUE TITLE
Input time/date is 5 minutes before alarm

### ISSUE THREAD

**Issue by HusDK** [Johboh/hassalarm#11]
First off, great work!!

Is it on purpose the update sent from the app is 5 minutes before the alarm?

**Comment by Johboh** [comment]
@HusDK hi!
Are you using a Samsung device? Then you might be experiencing https://eu.community.samsung.com/t5/Galaxy-S9-S9/Pie-Clock-app-bug/td-p/927333
A solution is to use another alarm clock then the Samsung one, for example the Google alarm clock.

**Comment by HusDK** [comment]
That was the problem, it works with google alarm clock.
Thanks
