### ISSUE TITLE
Can't get automation to trigger

### ISSUE THREAD

**Issue by Martinnygaard** [Johboh/hassalarm#13]
Hi,

I tried your app and intergtration, however, i ran into some problems.

In **Developer Tools -> States** i can see the next alarm on my phone (correct value)
![image](https://user-images.githubusercontent.com/26490587/76785636-173ffe00-67b6-11ea-84df-2b9250c27f13.png)

When entering the following test code in **Developer tools -> Templates**, i get empty string (a date in 1970):
```
{ states('sensor.date_time') }}
{{ state_attr('input_datetime.next_alarm', 'timestamp') }}
{{ state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', True) }}
```
I get this output:
![image](https://user-images.githubusercontent.com/26490587/76785953-a5b47f80-67b6-11ea-9b03-1f141cab84e2.png)

Why does the _input_datetime.next_alarm_ have the correct value in the states menu, but no value when testing the template? (neither when used in a automation)

Best regards,
Martin

**Comment by Martinnygaard** [comment]
And by the way: i just want to say that your app is just what i needed in Hassio.
Before i used a combination of Tasker and IFTTT to do this - but i'm very confident that once i get this up and running, it will be muchuch more simple!

Great work!

**Comment by Johboh** [comment]
Hello @Martinnygaard!
Can you confirm that you are actually sending the value from the app as in input_datetime, and not as a generic value? When you go to the configuration in the app make sure that the "legacy sensor" toggle is off. Did you also add the input_datetime sensor in your configuration in Hass?

**Comment by Johboh** [comment]
As explained here: https://github.com/Johboh/hassalarm/blob/master/README.md

**Comment by Martinnygaard** [comment]
That fixed it - embarrasing - was sure it was off.....

Now this code "{ states('sensor.date_time') }}" outputs a time for GMT. (I live in GMT+1, and therefor my alarms will trigger and reset one hour before the homeassistant think it's time to trigger.

Do you know how i can adjust it for GMT +1 aswell as summer/winter time?

**Comment by Martinnygaard** [comment]
This is my configuration.yaml:

![image](https://user-images.githubusercontent.com/26490587/76796830-904a5000-67cc-11ea-86a4-e288e163485c.png)

**Comment by Johboh** [comment]
@Martinnygaard that I'm unsure of. The sensor.date_time is a Hass date time sensor, maybe the Hass documentation have anything on this? Also, is your Hass host clock showing the correct date and time?

**Comment by Martinnygaard** [comment]
Okay.. You got me there aswell..

So the status now:
When i set an alarm at 16:40 on my phone, i see 16:40 in the **Developer Tools -> States**.
However, the timestamp (1584463200) is converting to 17:40 (not GMT+1 like my Hassio and phone)

![image](https://user-images.githubusercontent.com/26490587/76874147-0bfcd900-686f-11ea-8405-819f2974445e.png)



i can properly do some math somehow and subtract 3600 seconds, but isn't there a proper way of doing this?

I mean, the timestamp is something it is getting from the Hassalarm app (i assume), so is it possible for the app to take timezones in account?

**Comment by Johboh** [comment]
@Martinnygaard I will look into this once I'm back from vacation in less than a week (if they let me get home).

**Comment by Johboh** [comment]
@Martinnygaard this might be helpful: https://community.home-assistant.io/t/input-datetime-automation-wrong-time/144361
Are you using True or False as the last argument to the timestamp_custom(,) function?

**Comment by Martinnygaard** [comment]
> @Martinnygaard this might be helpful: https://community.home-assistant.io/t/input-datetime-automation-wrong-time/144361
> Are you using True or False as the last argument to the timestamp_custom(,) function?

That worked - it was true, and therefore comparing your timestamp to my local time.
Changing that to false, it must go back to GMT timzone (i guess) which your apps also sends (at least in the timestamp)

Thanks!
And enjoy your vacation.
