### ISSUE TITLE
Manage multiple device ?

### ISSUE THREAD

**Issue by Profil404** [Johboh/hassalarm#15]
Hi,

First thanks you for your app, this is the best and easiest way to sync my alarm with HA. With 1 device it work great but... any solution to use it with more than one device ? Like this:

- input_datetime.user1_next_alarm
- input_datetime.user2_next_alarm

It would be great, and with this feature we can make automation depending the user.

Benjamin

**Comment by Johboh** [comment]
@Profil404 hello!
Yes that should work. Add two input_datetime in your Hass configuration with different names (like you suggested above), and then just configure the same different Entity IDs in the app on the different devices.

**Comment by Profil404** [comment]
I'm stupid, I forgot that we could change the entity on the application...

This app is more amazing than I thinked :D 

Keep going and be safe ;)

**Comment by Profil404** [comment]
Mmmm' it's seem there is a bug with multiple device, only the first in the configuration file work, the following don't appear in the list of entities

**Comment by Johboh** [comment]
@Profil404 you mean only the first one shows up in Hass? How does your input_datetime Hass configuration looks like? Did you restart Hass?

**Comment by Profil404** [comment]
Yes, this is part of my configuration file: 

input_datetime:
  gm1913_next_alarm:
    name: Téléphone de Benjamin - Prochaine alarme
    has_date: true
    has_time: true
  oneplus_a6010_next_alarm:
    name: Téléphone de Noémie - Prochaine alarme
    has_date: true
    has_time: true

Of course I restarted HA after the change.

EDIT: Solved, browser cache history, thanks for your reactivity.

**Comment by Johboh** [comment]
@Profil404 great!
