### ISSUE TITLE
Won't work I think I have an issue with 12h vs 24 hr clock time

### ISSUE THREAD

**Issue by fourtrax01** [Johboh/hassalarm#16]
My automations won't trigger even though my next alarm is being updated and my date & time is correct, what I think may be the issue is that my alarm times reports as 8:30 AM and my date & time sensor is reporting on a 24 hour clock without Am/Pm so they never truly match and the automation never fires. Is there a way I can fix this?

**Comment by Johboh** [comment]
@fourtrax01 Hello!
Are you using the legacy sensor or the input_datetime sensor?

**Comment by fourtrax01** [comment]
Input_datetime.sensor

**Comment by Johboh** [comment]
@fourtrax01 What value do you see for the input_datetime when looking at it in hass? And how does your automation look like? Make sure you are comparing the current time using the correct time format.

**Comment by fourtrax01** [comment]
This is my value template from my automation, I don't know jinja so I just copied yours.
"{{ states('sensor.date_time') == (state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}"

**Comment by fourtrax01** [comment]
Date & Time
2020-03-26, 05:51

**Comment by fourtrax01** [comment]
![Screenshot_20200326-055432](https://user-images.githubusercontent.com/40325979/77649039-5b55a000-6f26-11ea-9955-503ced450921.png)

**Comment by Johboh** [comment]
Can you paste these in the template editor to get the values:
```
date_time: {{ states('sensor.date_time') }}
input timestamp: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int }}
input formatted: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', True) }}
input formatted 12h: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %I:%M %p', True) }}
```

**Comment by fourtrax01** [comment]
![Screenshot_20200326-061139](https://user-images.githubusercontent.com/40325979/77650522-dcae3200-6f28-11ea-9e07-65d8ed87e1a9.png)

**Comment by Johboh** [comment]
And what is your time now? 6:10am or 6:10pm :)?
and your alarm is set to 8:30am?

**Comment by fourtrax01** [comment]
![Screenshot_20200326-062046](https://user-images.githubusercontent.com/40325979/77651442-09af1480-6f2a-11ea-980a-4657fe219afe.png)

**Comment by fourtrax01** [comment]
6:21 am  alarm set for 8:30 am

**Comment by fourtrax01** [comment]
Does it matter that the date is formatted differently as well? My alarm reports March 26, 2020 not 2020-03-26 add the date

**Comment by Johboh** [comment]
And what if you set an alarm for one minute a head, open the hassalarm app and go in to "Test Connection" to force push a new value, then add these to the template editor:

```
date_time: {{ states('sensor.date_time') }}
input timestamp: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int }}
input formatted: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', True) }}
input formatted 12h: {{ state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %I:%M %p', True) }}
24h/True: {{ states('sensor.date_time') == (state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', True)) }}
12/True: {{ states('sensor.date_time') == (state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %I:%M', True)) }}
24/False {{ states('sensor.date_time') == (state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %H:%M', False)) }}
12/False {{ states('sensor.date_time') == (state_attr('input_datetime.next_alarm', 'timestamp') | int | timestamp_custom('%Y-%m-%d, %I:%M', False)) }}

```

**Comment by fourtrax01** [comment]
![Screenshot_20200326-064038](https://user-images.githubusercontent.com/40325979/77653303-c1452600-6f2c-11ea-9c06-5cdfaa379e3b.png)

**Comment by Johboh** [comment]
Well you have to wait until 06:42 before your do the evaluation :)

**Comment by fourtrax01** [comment]
My alarm went off but the automation didn't trigger

**Comment by fourtrax01** [comment]
Is the value template for my automation wrong?

**Comment by Johboh** [comment]
I want you to evaluate the expressions I posted above in the template editor during the same minute that your alarm is set to trigger, and see if any of the four expressions evaluates to True.

**Comment by fourtrax01** [comment]
Then I will have to do it on my computer a little later I can't copy and paste fast enough from my phone to get it all done in a minute. I'll try it out when I actually get up.
Thanks I'll let you know

**Comment by fourtrax01** [comment]
![Screenshot_20200326-065255](https://user-images.githubusercontent.com/40325979/77654603-80e6a780-6f2e-11ea-89d4-04623d02a609.png)

**Comment by Johboh** [comment]
Still the time is not aligned :). 06:51 vs 06:52

**Comment by fourtrax01** [comment]
![IMAG1309](https://user-images.githubusercontent.com/40325979/77672810-949e0800-6f46-11ea-812d-c41860a6cea4.jpg)

**Comment by fourtrax01** [comment]
Still false

**Comment by Johboh** [comment]
The problem now is because the alarm is set for tomorrow and not for today 😊. If you look at the date.

**Comment by fourtrax01** [comment]
![IMAG1310](https://user-images.githubusercontent.com/40325979/77674048-3bcf6f00-6f48-11ea-9781-bafa4df95bdb.jpg)

**Comment by fourtrax01** [comment]
The very second the alarm goes off home assistant changes the next scheduled alarm date for the next day, why? Those were one time alarms not recurring ones.

**Comment by Johboh** [comment]
Make sure you set an alarm which is not a repeated alarm.

**Comment by fourtrax01** [comment]
It was not a repeated alarm

**Comment by fourtrax01** [comment]
I turned off all other alarms set on my phone and turned battery optimization on for hassalarm app and finally got in to read true.
![IMAG1316](https://user-images.githubusercontent.com/40325979/77817983-26fbf400-708c-11ea-97f2-d28451c06318.jpg)
