### ISSUE TITLE
Showing alarm when none is

### ISSUE THREAD

**Issue by magicdave1** [Johboh/hassalarm#19]
Sometimes Hassalarm gets an alarm which is not set (see both screenshots). I am using the Google alarm clock app on Samsung S10e.

![Screenshot_20200626-085108_Clock](https://user-images.githubusercontent.com/14841376/86510079-0bbc2580-bded-11ea-81d4-21f18c59fd04.jpg)

![Screenshot_20200626-085100_Hassalarm](https://user-images.githubusercontent.com/14841376/86510083-137bca00-bded-11ea-9020-4144160aa956.jpg)

**Comment by Johboh** [comment]
Hej @magicdave1!
The most common reason for this is that there is another app (calendar app, reminder app, etc) that also publish itself as a "next alarm". Do you have any reminders set?

**Comment by magicdave1** [comment]
Hi @Johboh, thanks for your quick reply!
Actually I do have calendar reminders set. I just tested it and it showed that must have been it that set the next alarm. Any ways to exclude calendars from this?

**Comment by Johboh** [comment]
@magicdave1 What calendar are you using?
The OS API to get the next scheduled alarm clocks that Hassalarm is using in supposed to be used by alarm clocks only, but some non alarm clock apps also abuse this. I will investigate if its possible to figure out what app that actually set the alarm (might use https://developer.android.com/reference/android/app/AlarmManager.AlarmClockInfo#getShowIntent()) and then add some kind of filter for what intents to not include. However, there can only be one next alarm set at once. So if an app set themself as the next alarm, it's not possible to know what will be the next alarm after that.

**Comment by magicdave1** [comment]
@Johboh I am using the Google calendar app, so nothing extraordinary. It would be great if your possible solution would work.

**Comment by Johboh** [comment]
I do as well, but if I add a reminder in Google Calendar, its not detected by the app. Is it some custom samsung google calendar app?

**Comment by magicdave1** [comment]
That's weird. It is the regular app without any customization from Samsung.

![Screenshot_20200704-174312_Calendar](https://user-images.githubusercontent.com/14841376/86516081-01fee600-be1e-11ea-9515-53f705473f3c.jpg)

![Screenshot_20200704-174318_Hassalarm](https://user-images.githubusercontent.com/14841376/86516086-0a572100-be1e-11ea-9894-2339b050af05.jpg)

**Comment by magicdave1** [comment]
@Johboh Just let me know if I can test something or give you more informations

**Comment by benblb** [comment]
This is happening to me as well. I removed all permission from Samsung Calendar app (it sees no events). This app seems to be picking up Google Calendar Events.

**Comment by Johboh** [comment]
Looks like it's a Samsung issue:
https://us.community.samsung.com/t5/Galaxy-S10/Alarm-widget-shows-wrong-time-for-next-alarm/td-p/1189464
Related: https://eu.community.samsung.com/t5/mobile-apps-services/stock-alarm/td-p/1021438

I will look into adding a "ignore list" to ignore next scheduled alarms from specific apps, if possible.

**Comment by benblb** [comment]
Ah makes sense, thanks for checking it out and looking into a solution! Just wrote a Node-RED flow for waking my Hue lights today and this would allow me to get my alarm times in easily... Except for the Samsung hardware :p

PS apologies for double commenting for the same issue. A Google search landed me on the other & when I commented here I forgot to remove my comment on the other.

**Comment by Johboh** [comment]
@benblb @magicdave1 I just pushed a new version to Play Store with a very quick and dirty implementation where one can ignore certain apps from being reported. E.g. you can ignore the calendar app. Its added behind the "dotdotdot"/toolbar menu -> Ignore apps. Let me know how it works.

**Comment by magicdave1** [comment]
@Johboh it said that the next alarm is from an ignored app but unfortunately that alarm triggered again my lamps to turn on.

**Comment by Johboh** [comment]
@magicdave1 did you just ignore the app or have you had it running for a while? My guess is that it had already published the value before the ignore was added.

**Comment by benblb** [comment]
@Johboh I've been away from my laptop for a couple days, but WOW!!! So fast, thanks very much :) The fix worked great for me. If the next alarm is from an ignored app, it doesn't send anything. Once the next alarm is from a non-ignored app, it sends the trigger. My test will be tomorrow morning's alarm. Just completed my Node Red Hue wakeup flow.

**Comment by magicdave1** [comment]
@Johboh you were right with your guess. It is now perfectly working. Thank you so much for implementing this feature.

**Comment by Johboh** [comment]
@magicdave1 @benblb great! Let me know if you run in to any issues. I'm going to look over the implementation and improve it slightly as well.
