### ISSUE TITLE
Support for host without port

### ISSUE THREAD

**Issue by eifinger** [Johboh/hassalarm#2]
I am running hass behind a reverse proxy, thus I don't need/want a port.
Currently if no one is specified it automatically appends 8123 as the port.

**Comment by Johboh** [comment]
@eifinger I can add a text-box for that (or you can open a PR)

**Comment by Johboh** [comment]
@eifinger Or now when I think about it, you always have a port. Just set port 80 in your host, or 443 for ssl.

**Comment by eifinger** [comment]
It just worked for me, putting :443 to the end
