### ISSUE TITLE
Possible to show next alarm in HA card?

### ISSUE THREAD

**Issue by Jese44** [Johboh/hassalarm#25]
Hey, so I just got the hassalarm installed and I'd like to see my next alarm in a card in HA card, is it possible? if yes, how?
"Next alarm: tommorow OR mon,tue,wed..... at 00:00"

**Comment by Jese44** [comment]
Whoops, restarting did the thing and there was entity for next alarm. my bad.... Sorry for inconvenience. 
BUT is it possible to show the time in the card in DD:MM:YYY? and if I have alarm for tommorow, can it somehow show it like "Next scheduled alarm: Tommorow @ 12:00" instead of "2021-02-08, 12:00" (Tommorow, mon,tue,wed......)

**Comment by Johboh** [comment]
@Jese44 this is more of a generic "how to represent an input_datetime in a card" question and is better suited for the home assistant forum. I don't know the answer to this 😊.
