### ISSUE TITLE
crash if Google Alarm Clock is usd on huawei ANE-LX1

### ISSUE THREAD

**Issue by stortoaranci** [Johboh/hassalarm#26]
i'm not able to submit an alarm scheduled if the schedule comes from google alarm clock app. when i tap the homeassalarm's icon the app close immediately but it is still running.
the only way to interact with the application is to disable the scheduled alarms in google alarm clock.

let me know what can i do to help in solving the issue

**Comment by Johboh** [comment]
@stortoaranci hey!
Yes I can see in the crash logs that its crashing on startup. I will investigate and try provide a fix.

**Comment by Johboh** [comment]
@stortoaranci I have fixed this now and pushed a new version, 1.19, and it should propagate in to the Play Store soon.
Thanks for reporting!

**Comment by stortoaranci** [comment]
thank you very much. now it works like a charm
