### ISSUE TITLE
Feature Request: History of alarms

### ISSUE THREAD

**Issue by fusionstream** [Johboh/hassalarm#28]
Hi. A history of alarms would be cool; even if only 1.

I ask this because I'm hunting down an errant app that seems to be creating then immediately deleting an alarm.

A bit of backstory; I switched to this app after facing the same issue using the official Home Assistant app (where I have an automation that works with the Next Alarm sensor)

**Comment by Johboh** [comment]
Hi!
I can add a history view.

//Johan

**Comment by fusionstream** [comment]
Thanks!

A bit more news. While waiting I did a bit of tinkering with Node Red. Unfortunately, I discovered my package that is setting the alarm is "Unknown". 

Will await the next release! Thank you!

**Comment by Johboh** [comment]
@fusionstream This is now implemented and a new version (1.20) has been published to Google Play Store. It might take some hours before it gets verified and propagates. 

//Johan

**Comment by fusionstream** [comment]
Awesome. Many thanks!
