### ISSUE TITLE
Alarm has changed before automation can be triggered

### ISSUE THREAD

**Issue by pachi81** [Johboh/hassalarm#29]
Hi,
I´m still testing hassalarm on Samsung S10E and the next alarm value is triggered correct. 
I´m using an automation based on your example, but if the alarm is triggered on my phone, the next_alarm is set to the next one, immediately. 
These seems to happen so fast, that the automation is not triggered... 
Can you add some delay or do you have any idea, how can I solve the problem?
Thank you!

Regards, Michael

**Comment by Johboh** [comment]
I will look into it!

**Comment by pachi81** [comment]
Except the first call, the automation runs well at moment.
But I think a little delay (1-5 seconds) should not be a problem!?

**Comment by Johboh** [comment]
Yes I will look into this this weekend.

**Comment by Johboh** [comment]
@pachi81 I have added a delay now and uploaded a new version. Update to latest on Google play (it could take a couple of hours for the release to propagate). Let me know if it works!

**Comment by pachi81** [comment]
Hi @Johboh,

thank you very much! The App is still present and it seems to work!
History of the App and HA shows 5s delay.
The Automation will be triggered on monday the next time.
Great work! Thank you for your support!

Regards, Michael

**Comment by pachi81** [comment]
After some days testing, it works like expected! 
I also add a notification with the current value of the next_alarm entity, which was before already the next alert and now it is the current one triggering the automation.
Perfect! Great work! Thank you very much!!!

**Comment by Johboh** [comment]
Great to hear!
