### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [Johboh/hassalarm#31]
Are there any plans to make the app available outside of Google's walled garden – e.g. by providing the APK attached to its corresponding release tag here, or bringing it to F-Droid?

**Comment by Johboh** [comment]
I will look into it!

**Comment by IzzySoft** [comment]
Thanks! [Tagging releases](https://github.com/Johboh/hassalarm/releases) would be a first step (needed for either variant). Attaching the corresponding APK to each tag the second (and I then could look to integrating that with [my repo](https://apt.izzysoft.de/fdroid)) and would help pre-checking how it stands with matching F-Droid's inclusion criteria. If all seems fine, I could also help you proceeding to F-Droid (disclosure: I'm one of the maintainers there).

**Comment by Johboh** [comment]
I created a release now manually, but I will look into creating adding a CI/CD step for automatic publishing/releasing.

**Comment by IzzySoft** [comment]
Thanks! As promised, I've just added your app to my repo now (should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.fjun.hassalarm) with the next sync around 6 pm UTC). In order to do that, I had to establish metadata on my end – which I provide back to you with above mentioned PR (F-Droid will want that – and I prefer it, too, as it gives you control over descriptions and screenshots so they do not run out-of-date).

Scan results look good – so if you wish, after my PR has been merged this can be put forward to F-Droid I'd say.

**Comment by Johboh** [comment]
Thanks! Looks good, I merged the PR.

**Comment by IzzySoft** [comment]
Thanks a lot! Adjusted config at my end to check for updates there as well whenever a new release is being fetched. So any changes you make there should be reflected automatically (just let me know if you add other elements like per-release changelogs, so I have them checked as well).
