### ISSUE TITLE
Version 1.26 does not open, no alarm times are updated

### ISSUE THREAD

**Issue by benblb** [Johboh/hassalarm#33]
App version 1.26 immediately crashes. I have tried force-stopping + clearing the cache and I rebooted my phone. Didn't want to clear data quite yet. 

Galaxy S22 Ultra, One UI 6.1 (Android 14). 

Happy to provide additional info. Thanks for all your work on this app! It's the reason my lights fade on nicely in the morning before my alarm time.

**Comment by Johboh** [comment]
Oh no 😕. I bumped target SDK, something broke. I'm on it.

**Comment by benblb** [comment]
> Oh no 😕. I bumped target SDK, something broke. I'm on it.

Thanks so much! Fastest reply ever btw.

**Comment by Johboh** [comment]
I have fixed this now and pushed a new release, 1.27, to play store. Will take some hours for it to get verified and propagated.
Thanks for reporting! You can close this ticket if/when the crash is no longer happening.

**Comment by benblb** [comment]
Resolved, thanks so much! Confirmed fixed on my end.
