### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [Johboh/hassalarm#34]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, resulting APKs differ:

```diff
-------------------------------
--- /dev/fd/63  2024-07-22 13:49:55.081416991 +0200
+++ /dev/fd/62  2024-07-22 13:49:55.081416991 +0200
@@ -1,11 +1,11 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         d1f06b7f
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         e1612f97
+  32-bit CRC value (hex):                         17c98cce
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         ca05ad5b
   classes.dex
-  32-bit CRC value (hex):                         38d9f357
+  32-bit CRC value (hex):                         92ed9efe
   DebugProbesKt.bin
   32-bit CRC value (hex):                         7cded4df
   META-INF/androidx.activity_activity-ktx.version
```

Looking inside yours, and comparing with the commit behind the tag, the APK cannot have been built from that commit as the version bump only happens in the next commit. But when I build from that, the diff becomes huuuuge. So I assume the APK was built after the tag was created, with uncommitted local modifications applied. In which case RB is impossible.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by Johboh** [comment]
This should now be fixed.

**Comment by IzzySoft** [comment]
I hereby solemnly confirm: Yes, it is fixed with the latest release, thanks! :star_struck: So welcome to the hall-of-famous apps with Reproducible Builds! With the next sync around 6 pm UTC, when your latest release is pushed out to the IzzyOnDroid repo, it will carry the green shield for successful RB confirmation.

Thanks a lot!

PS: If you wish be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/com.fjun.hassalarm) e.g. from your Readme :smiley:

**Comment by IzzySoft** [comment]
Failed again for 1.34 today:

```diff
  -rw-r--r--  0.0 unx      120 b-      117 defN 1981-01-01 01:01:02 28580783 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx    10688 b-    10688 stor 1981-01-01 01:01:02 4fcdf714 assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx    10689 b-    10689 stor 1981-01-01 01:01:02 380a082e assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      576 b-      576 stor 1981-01-01 01:01:02 3e5c2ce9 assets/dexopt/baseline.profm
  -rw-r--r--  0.0 unx 30803520 b-  7086754 defN 1981-01-01 01:01:02 019b6817 classes.dex
  -rw-r--r--  0.0 unx     2844 b-     1052 defN 1981-01-01 01:01:02 7c1416aa classes2.dex
- -rw-r--r--  0.0 unx  9544984 b-  3526849 defN 1981-01-01 01:01:02 c0fe0bb2 classes3.dex
+ -rw-r--r--  0.0 unx  9544820 b-  3526786 defN 1981-01-01 01:01:02 1c50f791 classes3.dex
  -rw-r--r--  0.0 unx  5928672 b-  2084879 defN 1981-01-01 01:01:02 ddea4d57 classes4.dex
```

and the diff of `classes3` (about 160 kB) looks like it was either built from a different commit – or from a dirty tree (i.e. with local, uncommitted changes – or artifacts remaining from previous builds). Any clue, @Johboh?

**Comment by Johboh** [comment]
Let me take a look!
