### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by goosst** [Johboh/hassalarm#6]
Thanks for the very useful app. Do you have suggestions to easily automate the synchronization, in case I forget to start up the app?

e.g. 
- would there be a way of not having to push the button "Save and test connection" to synchronize everything? This would allow to start up the app with apps like MacroDroid or Tasker (e.g. every time I get connected to my wifi network, the sync occurs). 
- or would there be relevant parts of the app that could be easily added to a script which can be automatically called?

thanks!

**Comment by Johboh** [comment]
@goosst Hi!
The will sync automatically within an hour after you change the/set the alarm clock, or when the alarm clock schedule a new next alarm. I pushed a new version of the app that should do this within 1h after that the alarm clock is changed/set/updated.

**Comment by goosst** [comment]
Great, thanks!
